import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8');
assert(html.includes('const LARGE_PASTE_THRESHOLD=12000;'));
assert(html.includes("resolveLargePaste('file')"));
assert(html.includes("resolveLargePaste('text')"));
assert(html.includes("localStorage.setItem('jd-large-paste-choice',choice)"));
assert(html.includes("new File([pending.text]"));
assert(html.includes("await addSelectedFiles([file])"));
assert(html.includes("input.setRangeText(pending.text,start,end,'end')"));
assert(html.includes("e.clipboardData?.getData('text/plain')"));
console.log('PASS: large paste can be attached as a text file or pasted directly, with remembered choice.');
