import assert from 'node:assert/strict';import fs from 'node:fs';
const h=fs.readFileSync('index.html','utf8');
assert(h.includes('LONG RESPONSE MOBILE FLOW FIX'));
assert(h.includes('.code-container-wrap pre{max-height:none!important;overflow-x:auto!important;overflow-y:visible!important'));
assert(h.includes('.code-block-header{position:relative!important;top:auto!important}'));
assert(h.includes('function syncChatComposerReserve()'));
assert(h.includes('new ResizeObserver(syncChatComposerReserve)'));
assert(h.includes("'--jd-composer-reserve'"));
assert(h.includes('padding-bottom:calc(var(--jd-composer-reserve,112px) + 24px)!important'));
console.log('PASS: long code uses the main chat scroller and mobile bottom clearance follows the real composer height.');
