import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const source=fs.readFileSync('plugins.js','utf8');
const inject=fs.readFileSync('plugins-inject.js','utf8');
const values=new Map([['jd_plugins_v3_installed',JSON.stringify(['superpowers'])]]);
const input={value:'@Superpowers review this'};
const listeners={};
const fetchCalls=[];
const originalFetch=async(input,init)=>{fetchCalls.push({input,init});return new Response('ok');};
const document={querySelector:()=>input,readyState:'complete',addEventListener(){}};
const window={addEventListener:(type,fn)=>listeners[type]=fn,fetch:originalFetch,localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)}};
const sandbox={window,document,localStorage:window.localStorage,URL,Request,Response,console,setTimeout:fn=>{fn();return 1;}};
vm.runInNewContext(source,sandbox);
vm.runInNewContext(inject,sandbox);
assert.equal(window.JDPlugins.contextForChat().plugins[0].id,'superpowers');
await window.fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:input.value,plugins:window.JDPlugins.contextForChat()})});
assert.equal(fetchCalls.length,1);
const sent=JSON.parse(fetchCalls[0].init.body);
assert(sent.personalization.customInstructions.includes('[jd-plugins-active]'));
assert(sent.personalization.customInstructions.includes('Brainstorming'));
values.set('jd_plugins_v3_installed','[]');
input.value='@Superpowers review this';
assert.equal(window.JDPlugins.contextForChat().plugins.length,0,'uninstalled plugins cannot inject skills');
console.log('PASS: installed-only plugin skill injection works with the current marketplace context');
