import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const source=fs.readFileSync('plugins.js','utf8');
const page=fs.readFileSync('index.html','utf8');
assert.match(source,/var LS = 'jd_plugins_v3_installed'/);
assert.match(source,/function install\(id\)/);
assert.match(source,/function uninstall\(id\)/);
assert(source.includes("getCatalog: function () { return CATALOG; }"));
assert(page.includes('src="/plugins.js"')&&page.includes('href="/plugins.css"'));
const values=new Map([['jd_plugins_v3_installed',JSON.stringify(['superpowers'])]]);
const input={value:'@Superpowers review this change'};
const sandbox={window:{},document:{querySelector:()=>input},localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)}};
vm.runInNewContext(source,sandbox);
const plugins=sandbox.window.JDPlugins;
assert.equal(plugins.isInstalled('superpowers'),true);
assert.equal(plugins.contextForChat().superpowers.enabled,true);
assert.equal(plugins.contextForChat().plugins[0].id,'superpowers');
assert.equal(plugins.contextForChat().autoUse,true);
values.set('jd_plugins_v3_installed','[]');
assert.equal(plugins.contextForChat().superpowers.enabled,false);
assert.equal(plugins.contextForChat().plugins.length,0);
console.log('PASS: current Plugins install state, catalog, @mention context and uninstall revocation');
